# Generated by Django 4.0.3 on 2022-03-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedBooksShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphabetic_block', models.CharField(max_length=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='Cargos',
            new_name='Trolley',
        ),
        migrations.AddField(
            model_name='book',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paper',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='booked_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.studyspace'),
        ),
        migrations.AddField(
            model_name='profile',
            name='loaned_books',
            field=models.ManyToManyField(blank=True, to='main.book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='loaned_laptop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.laptop'),
        ),
        migrations.AddField(
            model_name='profile',
            name='loaned_papers',
            field=models.ManyToManyField(blank=True, to='main.paper'),
        ),
        migrations.AddField(
            model_name='studyspace',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LaptopDrawer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=5)),
                ('laptop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.laptop')),
            ],
        ),
    ]
